# Generated by Django 4.0.4 on 2023-11-04 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_category_pizzas_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzas',
            name='category',
        ),
        migrations.AddField(
            model_name='pizzas',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.category'),
        ),
    ]
