# Generated by Django 4.0.4 on 2023-11-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_pizzas_category_pizzas_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='pizza_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/images/'),
        ),
    ]
