# Generated by Django 4.0.4 on 2023-11-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_pizzas_pizza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzas',
            name='pizza_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/images/'),
        ),
    ]
